//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNH.XrmToolBox.DeleteRecordRecovery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FetchXMLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FetchXMLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NNH.XrmToolBox.DeleteRecordRecovery.FetchXMLResources", typeof(FetchXMLResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch version=&quot;1.0&quot; output-format=&quot;xml-platform&quot; mapping=&quot;logical&quot; distinct=&quot;false&quot; &gt;
        ///  &lt;entity name=&quot;systemuser&quot; &gt;
        ///    &lt;attribute name=&quot;fullname&quot; /&gt;
        ///    &lt;attribute name=&quot;systemuserid&quot; /&gt;
        ///    &lt;attribute name=&quot;isdisabled&quot; /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;accessmode&quot; operator=&quot;eq&quot; value=&quot;0&quot; /&gt;
        ///    &lt;/filter&gt;
        ///    &lt;order attribute=&quot;fullname&quot; /&gt;
        ///  &lt;/entity&gt;
        ///&lt;/fetch&gt;.
        /// </summary>
        internal static string GetAllUsersXML {
            get {
                return ResourceManager.GetString("GetAllUsersXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch&gt;
        ///  &lt;entity name=&quot;audit&quot; &gt;
        ///    &lt;attribute name=&quot;objecttypecodename&quot; /&gt;
        ///    &lt;attribute name=&quot;regardingobjectid&quot; /&gt;
        ///    &lt;attribute name=&quot;regardingobjectidname&quot; /&gt;
        ///    &lt;attribute name=&quot;createdon&quot; /&gt;
        ///    &lt;attribute name=&quot;userid&quot; /&gt;
        ///    &lt;attribute name=&quot;objectid&quot; /&gt;
        ///    &lt;attribute name=&quot;auditid&quot; /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;operation&quot; operator=&quot;eq&quot; value=&quot;3&quot; /&gt;
        ///      &lt;condition attribute=&quot;createdon&quot; operator=&quot;ge&quot;  value=&quot;{0}&quot; /&gt;
        ///      &lt;condition attribute=&quot;createdon&quot; operator=&quot;le [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeletedRecordsByUserXML {
            get {
                return ResourceManager.GetString("GetDeletedRecordsByUserXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fetch&gt;
        ///  &lt;entity name=&quot;audit&quot; &gt;
        ///    &lt;attribute name=&quot;objecttypecodename&quot; /&gt;
        ///    &lt;attribute name=&quot;regardingobjectid&quot; /&gt;
        ///    &lt;attribute name=&quot;regardingobjectidname&quot; /&gt;
        ///    &lt;attribute name=&quot;createdon&quot; /&gt;
        ///    &lt;attribute name=&quot;userid&quot; /&gt;
        ///    &lt;attribute name=&quot;objectid&quot; /&gt;
        ///    &lt;attribute name=&quot;auditid&quot; /&gt;
        ///    &lt;attribute name=&quot;objecttypecode&quot; /&gt;
        ///    &lt;attribute name=&quot;actionname&quot; /&gt;
        ///    &lt;attribute name=&quot;action&quot; /&gt;
        ///    &lt;attribute name=&quot;objectidname&quot; /&gt;
        ///    &lt;filter type=&quot;and&quot; &gt;
        ///      &lt;condition attribute=&quot;operation&quot; o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDeletedRecordsXML {
            get {
                return ResourceManager.GetString("GetDeletedRecordsXML", resourceCulture);
            }
        }
    }
}
